"""Deterministic, fixture-only Phase 3 evaluation foundation.

This package is intentionally additive and does not write the Phase 1/2 organism body.
"""

from .caregiver import (
    ACTIVE_SOURCE_KINDS,
    CAREGIVER_PROTOCOL_VERSION,
    AccountingStatus,
    CaregiverAccounting,
    CaregiverProposal,
    CaregiverRequest,
    CaregiverSource,
    CaregiverSourceKind,
    FixtureCaregiverAdapter,
    FixtureResponse,
    ProposalAuthority,
    ProposalKind,
    ProposalValidation,
    proposal_data_fields,
    proposal_from_text,
    validate_proposal,
)
from .fixtures import build_valid_fixture_episode
from .model import (
    ACCEPTED_PHASE3_REGISTRY_BYTES,
    ACCEPTED_PHASE3_REGISTRY_SHA256,
    CONTRACT_VERSION,
    IMPLEMENTATION_VERSION,
    Availability,
    AttemptState,
    CapabilityStatus,
    ConformanceResult,
    CostField,
    CostStatus,
    EpisodeEvidence,
    Point,
    accepted_phase3_requirement_ids,
)
from .rehearsal import (
    IntegratedCaregiverRehearsal,
    IntegratedRehearsalValidation,
    build_integrated_caregiver_rehearsal,
    validate_integrated_caregiver_rehearsal,
)
from .validation import (
    ReplayConflict,
    advance_attempt_history,
    classify_availability,
    reconcile_immutable_replay,
    validate_episode,
)

__all__ = [
    "ACCEPTED_PHASE3_REGISTRY_BYTES",
    "ACCEPTED_PHASE3_REGISTRY_SHA256",
    "ACTIVE_SOURCE_KINDS",
    "CAREGIVER_PROTOCOL_VERSION",
    "CONTRACT_VERSION",
    "IMPLEMENTATION_VERSION",
    "AccountingStatus",
    "Availability",
    "AttemptState",
    "CapabilityStatus",
    "CaregiverAccounting",
    "CaregiverProposal",
    "CaregiverRequest",
    "CaregiverSource",
    "CaregiverSourceKind",
    "ConformanceResult",
    "CostField",
    "CostStatus",
    "EpisodeEvidence",
    "FixtureCaregiverAdapter",
    "FixtureResponse",
    "IntegratedCaregiverRehearsal",
    "IntegratedRehearsalValidation",
    "Point",
    "ProposalAuthority",
    "ProposalKind",
    "ProposalValidation",
    "ReplayConflict",
    "accepted_phase3_requirement_ids",
    "advance_attempt_history",
    "build_integrated_caregiver_rehearsal",
    "build_valid_fixture_episode",
    "classify_availability",
    "proposal_data_fields",
    "proposal_from_text",
    "reconcile_immutable_replay",
    "validate_episode",
    "validate_integrated_caregiver_rehearsal",
    "validate_proposal",
]