from __future__ import annotations

from .model import (
    CONTRACT_VERSION,
    Availability,
    AttemptRecord,
    AttemptState,
    AvailabilityTransition,
    CaregivingRecord,
    CostClosure,
    DisablementProof,
    EpisodeBinding,
    EpisodeEvidence,
    EvaluationPointRecord,
    EvidenceIdentity,
    FIXTURE_ATTEMPT_ASSIGNMENT_RULE,
    FIXTURE_CLOSURE_BYTES_LIMIT,
    FIXTURE_CLOSURE_OPERATIONS_LIMIT,
    FIXTURE_COST_POLICY_ID,
    FIXTURE_MANIFEST_VERSION,
    FIXTURE_POPULATION_RECONCILIATION_RULE,
    FIXTURE_PROTECTED_CONFIGURATION_VERSION,
    FIXTURE_PUBLICATION_POLICY_VERSION,
    FIXTURE_RUN_GENERATION_RULE,
    FIXTURE_SEAL_BYTES_LIMIT,
    FIXTURE_SEAL_OPERATIONS_LIMIT,
    FIXTURE_STOPPING_RULE,
    FIXTURE_STUDY_PURPOSE,
    InformationFlowEvidence,
    InformationFlowInvocation,
    InformationFlowPolicy,
    MANDATORY_FAILURE_CONTROLS,
    Point,
    ProtectedSchedule,
    PublicationPolicy,
    PublicationSeal,
    ReviewedDraft,
    StudyManifest,
    TransitionKind,
    TransitionRecord,
    WRITER_ADMINISTRATION,
    WRITER_ORGANISM,
    digest_bytes,
    digest_record,
)
from ._fixture_helpers import (
    _base_substrates,
    _capability_results,
    _closure_payload_bytes,
    _cost_vector,
    _report_groups,
    _seal_payload_bytes,
    _sha,
    _substrate,
)


def build_valid_fixture_episode(*, repository_commit: str = "0" * 40) -> EpisodeEvidence:
    """Build the canonical synthetic W1 fixture used by protected Phase 3 tests.

    It exercises the accepted evidence mechanics but intentionally does not
    constitute a developmental-gain or maturity experiment.
    """
    schedule = ProtectedSchedule(
        version="phase3-fixture-schedule-v1",
        e1_cutoff_ordinal=7,
        e1_checkpoint_id="checkpoint:e1",
        e2_checkpoint_id="checkpoint:e2",
        before_availability=Availability.W0,
        after_availability=Availability.W1,
    )
    verifier_digest = _sha("phase3-conversion-verifier-v1")
    evaluator_digest = _sha("phase3-heldout-evaluator-v1")
    information_flow_policy = InformationFlowPolicy(
        version="phase3-info-flow-v1",
        verifier_digest=verifier_digest,
        evaluator_digest=evaluator_digest,
        verifier_input_store_id="store:verifier:input",
        verifier_output_store_id="store:verifier:output",
        evaluator_input_store_id="store:evaluator:input",
        evaluator_output_store_id="store:evaluator:output",
        verifier_path_id="path:verifier",
        evaluator_path_id="path:evaluator",
        verifier_cache_id="cache:verifier",
        evaluator_cache_id="cache:evaluator",
        verifier_probe_budget=1,
        verifier_retry_budget=0,
        permitted_feedback_fields=("verification_status",),
        permitted_feedback_recipients=("administration",),
        permitted_feedback_timing="preterminal_verifier_only",
        permitted_feedback_cardinality=1,
    )
    binding = EpisodeBinding(
        study_id="study:fixture-foundation",
        attempt_id="attempt:fixture-001",
        attempt_ordinal=1,
        episode_id="episode:fixture-001",
        organism_id="sudachi-fixture-0",
        lineage_generation=0,
        database_schema_version=2,
        base_contract_version="minimal-organism-contract/v0.2",
        environment_version="phase3-fixture-environment-v1",
        capability_suite_version="phase3-fixture-suite-v1",
        capability_suite_digest=_sha("phase3-fixture-suite-v1"),
        outcome_evaluator_version="phase3-heldout-evaluator-v1",
        outcome_evaluator_digest=evaluator_digest,
        conversion_verifier_version="phase3-conversion-verifier-v1",
        conversion_verifier_digest=verifier_digest,
        information_flow_policy_version=information_flow_policy.version,
        information_flow_policy_digest=information_flow_policy.canonical_digest(),
        schedule_version=schedule.version,
        schedule_digest=schedule.canonical_digest(),
        protected_budget_version="phase1-v1",
        protected_configuration_version=FIXTURE_PROTECTED_CONFIGURATION_VERSION,
        baseline_checkpoint_id="checkpoint:e0",
        caregiver_condition_id="deterministic-fixture",
        substrate_baseline_condition_id="fixture-baseline-v1",
        fixture_case_id="fixture:w1-retained-rule",
        contract_version=CONTRACT_VERSION,
    )
    publication_policy = PublicationPolicy(
        version=FIXTURE_PUBLICATION_POLICY_VERSION,
        closure_operations_limit=FIXTURE_CLOSURE_OPERATIONS_LIMIT,
        closure_bytes_limit=FIXTURE_CLOSURE_BYTES_LIMIT,
        seal_operations_limit=FIXTURE_SEAL_OPERATIONS_LIMIT,
        seal_bytes_limit=FIXTURE_SEAL_BYTES_LIMIT,
    )
    attempt = AttemptRecord(
        attempt_id=binding.attempt_id,
        ordinal=1,
        state=AttemptState.COMPLETED_SUCCESSFUL,
        state_history=(
            AttemptState.SCHEDULED,
            AttemptState.STARTED,
            AttemptState.COMPLETED_SUCCESSFUL,
        ),
        episode_id=binding.episode_id,
        organism_id=binding.organism_id,
        lineage_generation=binding.lineage_generation,
    )
    study = StudyManifest(
        study_id=binding.study_id,
        manifest_version=FIXTURE_MANIFEST_VERSION,
        study_purpose=FIXTURE_STUDY_PURPOSE,
        claim_tier="deterministic_conformance",
        deterministic_run_generation_rule=FIXTURE_RUN_GENERATION_RULE,
        planned_attempt_ordinals=(1,),
        exact_attempt_count=1,
        stopping_rule=FIXTURE_STOPPING_RULE,
        attempt_assignment_rule=FIXTURE_ATTEMPT_ASSIGNMENT_RULE,
        required_failure_controls=MANDATORY_FAILURE_CONTROLS,
        comparison_family_conditions=(),
        population_reconciliation_rule=FIXTURE_POPULATION_RECONCILIATION_RULE,
        attempt_records=(attempt,),
        suite_digest=binding.capability_suite_digest,
        evaluator_digest=binding.outcome_evaluator_digest,
        verifier_digest=binding.conversion_verifier_digest,
        information_flow_policy_digest=binding.information_flow_policy_digest,
        schedule_digest=binding.schedule_digest,
        cost_policy_id=FIXTURE_COST_POLICY_ID,
        publication_policy=publication_policy,
    )
    care_payload = b"fixture demonstration: map marker-alpha to capability success"
    caregiving = CaregivingRecord(
        record_id="caregiving:fixture-001",
        binding=binding,
        assistance_class="demonstration",
        content_digest=digest_bytes(care_payload),
        content_size_bytes=len(care_payload),
        terminal_outcome="accepted",
        terminal=True,
        ordinal=2,
    )
    candidate_id = "substrate:fixture-rule"
    transitions = (
        TransitionRecord(
            transition_id="conversion:fixture-001",
            kind=TransitionKind.CONVERSION,
            binding=binding,
            writer=WRITER_ORGANISM,
            status="produced",
            ordinal=3,
            input_id=caregiving.record_id,
            output_id=candidate_id,
            payload_digest=digest_record("sudachi.phase3.transition_payload/v1", {"kind": "conversion", "candidate": candidate_id}),
        ),
        TransitionRecord(
            transition_id="verification:fixture-001",
            kind=TransitionKind.VERIFICATION,
            binding=binding,
            writer=WRITER_ADMINISTRATION,
            status="passed",
            ordinal=4,
            input_id="conversion:fixture-001",
            output_id="verification:evidence-001",
            payload_digest=digest_record("sudachi.phase3.transition_payload/v1", {"kind": "verification", "passed": True}),
        ),
        TransitionRecord(
            transition_id="adoption:fixture-001",
            kind=TransitionKind.ADOPTION,
            binding=binding,
            writer=WRITER_ADMINISTRATION,
            status="accepted",
            ordinal=5,
            input_id="verification:fixture-001",
            output_id="adoption:accepted-001",
            payload_digest=digest_record("sudachi.phase3.transition_payload/v1", {"kind": "adoption", "accepted": True}),
        ),
        TransitionRecord(
            transition_id="activation:fixture-001",
            kind=TransitionKind.ACTIVATION,
            binding=binding,
            writer=WRITER_ADMINISTRATION,
            status="activated",
            ordinal=6,
            input_id="adoption:fixture-001",
            output_id=candidate_id,
            payload_digest=digest_record("sudachi.phase3.transition_payload/v1", {"kind": "activation", "candidate": candidate_id}),
            source_checkpoint_id=binding.baseline_checkpoint_id,
            destination_checkpoint_id=schedule.e1_checkpoint_id,
        ),
    )
    transition_ids = tuple(record.transition_id for record in transitions)
    rule_payload = b"fixture-rule-v1: marker-alpha -> pass"

    e0_identity = EvidenceIdentity.from_binding(
        binding,
        point=Point.E0,
        cutoff_ordinal=schedule.e1_cutoff_ordinal,
        checkpoint_id=binding.baseline_checkpoint_id,
    )
    e1_identity = EvidenceIdentity.from_binding(
        binding,
        point=Point.E1,
        cutoff_ordinal=schedule.e1_cutoff_ordinal,
        checkpoint_id=schedule.e1_checkpoint_id,
    )
    e2_identity = EvidenceIdentity.from_binding(
        binding,
        point=Point.E2,
        cutoff_ordinal=schedule.e1_cutoff_ordinal,
        checkpoint_id=schedule.e2_checkpoint_id,
    )

    e0 = EvaluationPointRecord(
        identity=e0_identity,
        point=Point.E0,
        ordinal=1,
        availability=Availability.W0,
        checkpoint_id=binding.baseline_checkpoint_id,
        integrity_valid=True,
        infrastructure_valid=True,
        reachable=True,
        suite_complete=True,
        evaluator_sequestered=True,
        capability_results=_capability_results(binding, Point.E0, binding.baseline_checkpoint_id, schedule.e1_cutoff_ordinal),
        substrates=_base_substrates(binding, Point.E0, binding.baseline_checkpoint_id),
        cumulative_cost=_cost_vector("e0", e0_identity),
    )
    rule_e1 = _substrate(
        binding=binding,
        point=Point.E1,
        checkpoint_id=schedule.e1_checkpoint_id,
        substrate_id=candidate_id,
        substrate_class="rule",
        payload=rule_payload,
        custodian="organism",
        origin="caregiver_derived",
        executable=True,
        caregiver_ids=(caregiving.record_id,),
        transition_ids=transition_ids,
        w1_permitted=True,
        capability_dependency="capability:fixture-transform",
    )
    e1 = EvaluationPointRecord(
        identity=e1_identity,
        point=Point.E1,
        ordinal=8,
        availability=Availability.W0,
        checkpoint_id=schedule.e1_checkpoint_id,
        integrity_valid=True,
        infrastructure_valid=True,
        reachable=True,
        suite_complete=True,
        evaluator_sequestered=True,
        capability_results=_capability_results(binding, Point.E1, schedule.e1_checkpoint_id, schedule.e1_cutoff_ordinal),
        substrates=_base_substrates(binding, Point.E1, schedule.e1_checkpoint_id) + (rule_e1,),
        cumulative_cost=_cost_vector("e1", e1_identity),
    )
    rule_e2 = _substrate(
        binding=binding,
        point=Point.E2,
        checkpoint_id=schedule.e2_checkpoint_id,
        substrate_id=candidate_id,
        substrate_class="rule",
        payload=rule_payload,
        custodian="organism",
        origin="caregiver_derived",
        executable=True,
        caregiver_ids=(caregiving.record_id,),
        transition_ids=transition_ids,
        w1_permitted=True,
        capability_dependency="capability:fixture-transform",
    )
    availability_transition = AvailabilityTransition(
        transition_id="availability:fixture-001",
        binding=binding,
        writer=WRITER_ADMINISTRATION,
        before=Availability.W0,
        after=Availability.W1,
        source_checkpoint_id=schedule.e1_checkpoint_id,
        destination_checkpoint_id=schedule.e2_checkpoint_id,
        applied=True,
        ordinal=9,
        payload_digest=digest_record(
            "sudachi.phase3.availability_transition/v1",
            {
                "before": "W0",
                "after": "W1",
                "source": schedule.e1_checkpoint_id,
                "destination": schedule.e2_checkpoint_id,
                "writer": WRITER_ADMINISTRATION,
                "ordinal": 9,
            },
        ),
    )
    e2 = EvaluationPointRecord(
        identity=e2_identity,
        point=Point.E2,
        ordinal=10,
        availability=Availability.W1,
        checkpoint_id=schedule.e2_checkpoint_id,
        integrity_valid=True,
        infrastructure_valid=True,
        reachable=True,
        suite_complete=True,
        evaluator_sequestered=True,
        capability_results=_capability_results(binding, Point.E2, schedule.e2_checkpoint_id, schedule.e1_cutoff_ordinal),
        substrates=_base_substrates(binding, Point.E2, schedule.e2_checkpoint_id) + (rule_e2,),
        cumulative_cost=_cost_vector("e2", e2_identity),
    )
    disablement = DisablementProof(
        identity=e2_identity,
        schedule_digest=binding.schedule_digest,
        transition_id=availability_transition.transition_id,
        writer=WRITER_ADMINISTRATION,
        source_checkpoint_id=schedule.e1_checkpoint_id,
        destination_checkpoint_id=schedule.e2_checkpoint_id,
        live_adapter_handles=0,
        post_cutoff_dispatches=0,
        post_cutoff_human_bridges=0,
        post_cutoff_model_calls=0,
        post_cutoff_network_calls=0,
        post_cutoff_subprocess_calls=0,
        post_cutoff_human_interventions=0,
        post_cutoff_caregiver_cost_units=0,
        queued_or_cached_usable_outputs=0,
        guarded_imports_passed=True,
        source_inspection_passed=True,
        alternate_path_probes_passed=True,
        independently_reconstructed=True,
    )
    invocations = (
        InformationFlowInvocation(
            invocation_id="evaluator:e0:001",
            identity=e0_identity,
            role="evaluator",
            ordinal=1,
            input_digest=_sha("heldout-evaluator-e0-input"),
            output_digest=_sha("heldout-evaluator-e0-output"),
            probe_ordinal=0,
            retry_ordinal=0,
            disclosed_fields=(),
            recipients=("protected_evidence_store",),
            disclosure_timing="protected_only",
            contains_heldout_material=True,
            derivative_of_heldout=False,
            evaluator_targeted_artifact=False,
        ),
        InformationFlowInvocation(
            invocation_id="verifier:e1:001",
            identity=e1_identity,
            role="verifier",
            ordinal=4,
            input_digest=_sha("conversion-verifier-input"),
            output_digest=_sha("conversion-verifier-output"),
            probe_ordinal=1,
            retry_ordinal=0,
            disclosed_fields=("verification_status",),
            recipients=("administration",),
            disclosure_timing="preterminal_verifier_only",
            contains_heldout_material=False,
            derivative_of_heldout=False,
            evaluator_targeted_artifact=False,
        ),
        InformationFlowInvocation(
            invocation_id="evaluator:e1:001",
            identity=e1_identity,
            role="evaluator",
            ordinal=8,
            input_digest=_sha("heldout-evaluator-e1-input"),
            output_digest=_sha("heldout-evaluator-e1-output"),
            probe_ordinal=0,
            retry_ordinal=0,
            disclosed_fields=(),
            recipients=("protected_evidence_store",),
            disclosure_timing="protected_only",
            contains_heldout_material=True,
            derivative_of_heldout=False,
            evaluator_targeted_artifact=False,
        ),
        InformationFlowInvocation(
            invocation_id="evaluator:e2:001",
            identity=e2_identity,
            role="evaluator",
            ordinal=10,
            input_digest=_sha("heldout-evaluator-e2-input"),
            output_digest=_sha("heldout-evaluator-e2-output"),
            probe_ordinal=0,
            retry_ordinal=0,
            disclosed_fields=(),
            recipients=("protected_evidence_store",),
            disclosure_timing="protected_only",
            contains_heldout_material=True,
            derivative_of_heldout=False,
            evaluator_targeted_artifact=False,
        ),
    )
    information_flow = InformationFlowEvidence(
        identity=e2_identity,
        invocations=invocations,
        heldout_access_before_terminal=0,
        derivative_leaks=0,
        probe_budget_exceeded=False,
        retry_budget_exhausted=False,
        evaluator_targeted_artifact=False,
    )
    final_cost = _cost_vector("final", e2_identity)
    points = (e0, e1, e2)
    groups = _report_groups(
        binding=binding,
        study=study,
        caregiving_records=(caregiving,),
        transitions=transitions,
        points=points,
        disablement=disablement,
        information_flow_policy=information_flow_policy,
        information_flow=information_flow,
        final_cost=final_cost,
        terminal_state=AttemptState.COMPLETED_SUCCESSFUL,
        repository_commit=repository_commit,
    )
    draft = ReviewedDraft(identity=e2_identity, groups=groups, prepared_ordinal=11, reviewed=True)
    draft_digest = draft.canonical_digest()
    final_cost_digest = final_cost.canonical_digest()
    closure = CostClosure(
        identity=e2_identity,
        closure_id="cost-closure:fixture-001",
        draft_digest=draft_digest,
        cost_vector_digest=final_cost_digest,
        closed_after_ordinal=12,
        vector_reconciled=True,
        all_in_scope_work_complete=True,
        late_in_scope_cost_count=0,
        unmatched_event_count=0,
        visible_unmeasured_labor_count=0,
        operations_used=1,
        bytes_used=_closure_payload_bytes(draft_digest=draft_digest, cost_vector_digest=final_cost_digest),
    )
    closure_digest = closure.canonical_digest()
    seal = PublicationSeal(
        identity=e2_identity,
        seal_id="publication-seal:fixture-001",
        draft_digest=draft_digest,
        closure_digest=closure_digest,
        operations_used=1,
        bytes_used=_seal_payload_bytes(draft_digest=draft_digest, closure_digest=closure_digest),
        retries=0,
        semantic_edits=0,
    )
    return EpisodeEvidence(
        binding=binding,
        schedule=schedule,
        study=study,
        caregiving_records=(caregiving,),
        transitions=transitions,
        availability_transition=availability_transition,
        points=points,
        disablement=disablement,
        information_flow_policy=information_flow_policy,
        information_flow=information_flow,
        final_cost=final_cost,
        reviewed_draft=draft,
        cost_closure=closure,
        publication_seal=seal,
        terminal_attempt_state=AttemptState.COMPLETED_SUCCESSFUL,
        repository_commit=repository_commit,
        limitations=(
            "fixture-only deterministic mechanics",
            "no developmental-gain claim",
            "no live caregiver, provider, model update, memory, skill generation, or action execution",
        ),
    )
